/**
 * AutoFeed AI – AI Question Bank
 * Provides role+purpose specific questions and response options
 */

const QUESTION_BANK = {

    // ============ STUDENT ============
    Student: {
        Performance: [
            { q: "How consistently do you complete your assignments and studies on time?", type: "scale", category: "Time Management" },
            { q: "When you face a difficult subject, what is your typical approach?", type: "options", options: ["I study harder and seek extra help", "I focus on easier subjects first", "I feel overwhelmed and delay it", "I ask peers to help me understand"], category: "Resilience" },
            { q: "How often do you review your notes after class?", type: "scale", category: "Study Habits" },
            { q: "Describe a time you overcame a major academic challenge:", type: "text", category: "Problem Solving" },
            { q: "How do you prioritize multiple deadlines at once?", type: "options", options: ["I create a schedule and stick to it", "I work on the most urgent first", "I try to do everything simultaneously", "I often miss deadlines"], category: "Organization" },
            { q: "How well do you understand your own learning style?", type: "scale", category: "Self-Awareness" },
            { q: "How often do you set academic goals for yourself?", type: "scale", category: "Goal Setting" },
            { q: "When you receive a poor grade, how do you respond?", type: "options", options: ["Analyze mistakes and improve strategy", "Feel discouraged but try again", "Blame external factors", "Discuss with teacher for guidance"], category: "Growth Mindset" },
            { q: "How comfortable are you asking questions in class?", type: "scale", category: "Communication" },
            { q: "Describe your ideal study environment:", type: "text", category: "Self-Awareness" },
        ],
        Communication: [
            { q: "How comfortable are you presenting ideas in front of the class?", type: "scale", category: "Public Speaking" },
            { q: "When working on a group project, what role do you naturally take?", type: "options", options: ["Coordinator/Planner", "Creative contributor", "Researcher/Analyst", "Supporter/Helper"], category: "Team Role" },
            { q: "How do you handle disagreements with classmates?", type: "options", options: ["Discuss calmly to find a solution", "Avoid conflict and agree", "Stand firm on my position", "Seek teacher mediation"], category: "Conflict Resolution" },
            { q: "How well do you express your ideas in writing?", type: "scale", category: "Written Communication" },
            { q: "How do you respond when a classmate needs help?", type: "options", options: ["Proactively offer assistance", "Help when asked", "Direct them to the teacher", "It depends on my own workload"], category: "Empathy" },
            { q: "Describe a situation where you effectively communicated a complex idea:", type: "text", category: "Communication" },
            { q: "How actively do you participate in class discussions?", type: "scale", category: "Engagement" },
            { q: "How well do you listen when others are speaking?", type: "scale", category: "Active Listening" },
            { q: "How easy is it for you to give constructive feedback to peers?", type: "scale", category: "Feedback" },
            { q: "What is your biggest communication challenge in academic settings?", type: "text", category: "Self-Assessment" },
        ],
        Teamwork: [
            { q: "How do you contribute when you disagree with a team decision?", type: "options", options: ["Voice my concern and accept the majority", "Try to convince others before deciding", "Go along to avoid conflict", "Propose a compromise"], category: "Collaboration" },
            { q: "How well do you adapt your working style to suit your team?", type: "scale", category: "Adaptability" },
            { q: "How proactively do you check on teammates' progress?", type: "scale", category: "Team Support" },
            { q: "When a teammate underperforms, what do you do?", type: "options", options: ["Offer help and extra support", "Report to the teacher/supervisor", "Cover for them silently", "Address it directly with them"], category: "Conflict Resolution" },
            { q: "Describe your best teamwork experience:", type: "text", category: "Reflection" },
            { q: "How comfortable are you taking the lead in a group project?", type: "scale", category: "Leadership" },
            { q: "How do you ensure fairness in task distribution?", type: "options", options: ["Discuss openly as a group", "Assign based on strengths", "Let the leader decide", "Volunteer for tasks I like"], category: "Fairness" },
            { q: "How often do you celebrate team wins?", type: "scale", category: "Team Culture" },
            { q: "What makes you a valuable team member?", type: "text", category: "Self-Reflection" },
            { q: "How well do you handle criticism from teammates?", type: "scale", category: "Resilience" },
        ],
        Leadership: [
            { q: "Have you ever voluntarily led a school group or project?", type: "options", options: ["Yes, frequently", "Yes, a few times", "Once or twice", "Not yet but I want to"], category: "Leadership Experience" },
            { q: "How do you motivate peers who are losing interest?", type: "text", category: "Motivation" },
            { q: "How confident are you in making decisions for a group?", type: "scale", category: "Decision Making" },
            { q: "When leading a group, how do you delegate tasks?", type: "options", options: ["Based on each person's strengths", "By asking for volunteers", "Randomly/by availability", "I do most tasks myself"], category: "Delegation" },
            { q: "How do you handle it when your leadership is questioned?", type: "options", options: ["Listen and reflect openly", "Defend my decisions calmly", "Feel upset but continue", "Reconsider the approach"], category: "Resilience" },
            { q: "How well can you inspire others with your vision?", type: "scale", category: "Inspiration" },
            { q: "Describe a moment you took initiative without being asked:", type: "text", category: "Initiative" },
            { q: "How do you ensure all team voices are heard?", type: "scale", category: "Inclusivity" },
            { q: "How do you handle failure in a leadership role?", type: "options", options: ["Reflect and learn from it", "Blame the team situation", "Give up leadership roles", "Seek mentorship and guidance"], category: "Growth Mindset" },
            { q: "What kind of leader do you aspire to be?", type: "text", category: "Vision" },
        ],
        Creativity: [
            { q: "When given a creative project, what is your typical approach?", type: "options", options: ["Research and brainstorm many ideas", "Start immediately with the first idea", "Wait for inspiration to strike", "Collaborate with others for ideas"], category: "Creative Process" },
            { q: "How often do you challenge conventional methods in your work?", type: "scale", category: "Innovation" },
            { q: "Describe your most creative school project:", type: "text", category: "Reflection" },
            { q: "How do you handle creative blocks?", type: "options", options: ["Take a break and return fresh", "Push through the block", "Ask for help or inspiration", "Change the topic or approach"], category: "Resilience" },
            { q: "How open are you to unconventional ideas from others?", type: "scale", category: "Open-mindedness" },
            { q: "How do you balance creativity with academic structure?", type: "scale", category: "Balance" },
            { q: "Which best describes your creative thinking style?", type: "options", options: ["Divergent: many ideas at once", "Convergent: one well-polished idea", "Conceptual: big-picture thinking", "Practical: applied and actionable"], category: "Learning Style" },
            { q: "How frequently do you experiment with new learning methods?", type: "scale", category: "Experimentation" },
            { q: "What is your biggest source of creative inspiration?", type: "text", category: "Inspiration" },
            { q: "How comfortable are you sharing unfinished creative ideas?", type: "scale", category: "Vulnerability" },
        ],
        "Problem Solving": [
            { q: "When you face an unfamiliar problem, what do you do first?", type: "options", options: ["Break it into smaller parts", "Research similar problems", "Ask for help immediately", "Try multiple solutions quickly"], category: "Strategy" },
            { q: "How confident are you in solving complex problems independently?", type: "scale", category: "Self-Reliance" },
            { q: "Describe a difficult academic problem you solved creatively:", type: "text", category: "Reflection" },
            { q: "How do you react when your first solution fails?", type: "options", options: ["Try a different approach", "Seek guidance from a teacher", "Give up and move on", "Analyze what went wrong first"], category: "Resilience" },
            { q: "How often do you apply knowledge from one subject to solve problems in another?", type: "scale", category: "Interdisciplinary Thinking" },
            { q: "How well do you handle ambiguous or open-ended problems?", type: "scale", category: "Ambiguity Tolerance" },
            { q: "What problem-solving method do you rely on most?", type: "options", options: ["Logical/Analytical", "Trial and Error", "Creative/Lateral thinking", "Collaborative brainstorming"], category: "Style" },
            { q: "How often do you evaluate your problem-solving process after completion?", type: "scale", category: "Reflection" },
            { q: "What was the most complex problem you've ever had to solve?", type: "text", category: "Experience" },
            { q: "How effectively do you use available resources (books, internet, people) when stuck?", type: "scale", category: "Resourcefulness" },
        ],
    },

    // ============ EMPLOYEE ============
    Employee: {
        Performance: [
            { q: "How consistently do you meet your assigned deadlines at work?", type: "scale", category: "Reliability" },
            { q: "How do you handle a situation where your workload exceeds your capacity?", type: "options", options: ["Prioritize and communicate with my manager", "Work overtime without telling anyone", "Ask a colleague for help", "Delay lower-priority tasks"], category: "Workload Management" },
            { q: "How would you rate your ability to deliver quality work under tight deadlines?", type: "scale", category: "Quality Under Pressure" },
            { q: "Describe a significant achievement in your current role:", type: "text", category: "Accomplishments" },
            { q: "How proactively do you seek feedback on your work performance?", type: "scale", category: "Growth Mindset" },
            { q: "How well do you manage competing priorities?", type: "options", options: ["Organize by impact and urgency", "Follow my manager's direction", "Handle one thing at a time", "Struggle to prioritize effectively"], category: "Prioritization" },
            { q: "How comfortable are you taking ownership of mistakes?", type: "scale", category: "Accountability" },
            { q: "How often do you go above and beyond your defined job responsibilities?", type: "scale", category: "Initiative" },
            { q: "What is your biggest professional development goal right now?", type: "text", category: "Career Growth" },
            { q: "How effectively do you apply newly learned skills in your work?", type: "scale", category: "Learning Application" },
        ],
        Leadership: [
            { q: "Do you naturally guide or mentor junior colleagues?", type: "scale", category: "Mentoring" },
            { q: "Describe a situation where you led a project or initiative:", type: "text", category: "Leadership Experience" },
            { q: "How do you influence your team without formal authority?", type: "options", options: ["Build trust and lead by example", "Use persuasion and data", "Rely on relationships", "I prefer not to influence informally"], category: "Influence" },
            { q: "How comfortable are you making decisions when your manager is unavailable?", type: "scale", category: "Autonomy" },
            { q: "How do you handle team members who are resistant to change?", type: "options", options: ["Explain the reasoning and benefits", "Involve them in the change process", "Escalate to management", "Give them time to adjust"], category: "Change Management" },
            { q: "How effectively do you resolve conflicts within your team?", type: "scale", category: "Conflict Resolution" },
            { q: "What leadership style do you identify with most?", type: "options", options: ["Transformational: inspire with vision", "Servant: support others' needs", "Coaching: develop team members", "Democratic: collaborative decision-making"], category: "Style" },
            { q: "How do you ensure your team members feel heard and valued?", type: "text", category: "Empathy" },
            { q: "How well do you delegate tasks appropriately?", type: "scale", category: "Delegation" },
            { q: "How do you handle the pressure of having others depend on your decisions?", type: "scale", category: "Resilience" },
        ],
        Communication: [
            { q: "How clearly do you articulate complex technical ideas to non-technical colleagues?", type: "scale", category: "Clarity" },
            { q: "How do you prefer to communicate important updates?", type: "options", options: ["Email with full details", "Quick team meeting", "Direct one-on-one conversation", "Collaborative document or chat"], category: "Communication Style" },
            { q: "How well do you adapt your communication to different audiences?", type: "scale", category: "Adaptability" },
            { q: "Describe a situation where miscommunication caused a work issue and how you resolved it:", type: "text", category: "Conflict Resolution" },
            { q: "How confident are you in giving presentations or public speaking?", type: "scale", category: "Public Speaking" },
            { q: "How proactively do you share information with your team?", type: "scale", category: "Transparency" },
            { q: "How effectively do you give constructive feedback?", type: "scale", category: "Feedback" },
            { q: "How actively do you listen during meetings and conversations?", type: "options", options: ["Take notes and ask questions", "Listen attentively without notes", "Listen while multitasking", "Participate when directly asked"], category: "Active Listening" },
            { q: "How do you handle professional disagreements?", type: "options", options: ["Address openly and respectfully", "Seek common ground", "Defer to the senior person", "Avoid confrontation"], category: "Assertiveness" },
            { q: "What aspect of your communication would you most like to improve?", type: "text", category: "Self-Awareness" },
        ],
        Teamwork: [
            { q: "How well do you collaborate with colleagues who have different work styles?", type: "scale", category: "Adaptability" },
            { q: "When a team project is struggling, what is your response?", type: "options", options: ["Step up and help reorganize efforts", "Communicate the issue to management", "Focus on my own tasks first", "Support teammates informally"], category: "Initiative" },
            { q: "How regularly do you recognize and appreciate colleagues' contributions?", type: "scale", category: "Recognition" },
            { q: "Describe the best team you've worked in and what made it effective:", type: "text", category: "Reflection" },
            { q: "How comfortably do you share credit for team achievements?", type: "scale", category: "Humility" },
            { q: "How do you handle interpersonal friction within your team?", type: "options", options: ["Address it directly with the person", "Mediate between all parties", "Report to HR or management", "Allow time to resolve naturally"], category: "Conflict Resolution" },
            { q: "How invested are you in your team's overall success, beyond your own role?", type: "scale", category: "Commitment" },
            { q: "How effectively do you manage remote collaboration?", type: "scale", category: "Remote Work" },
            { q: "What is your biggest strength as a team member?", type: "text", category: "Self-Assessment" },
            { q: "How well do you give and receive constructive criticism in a team context?", type: "scale", category: "Feedback" },
        ],
        Creativity: [
            { q: "How often do you propose new ideas or process improvements at work?", type: "scale", category: "Innovation" },
            { q: "Describe a creative solution you implemented in a workplace challenge:", type: "text", category: "Innovation" },
            { q: "How do you respond when your creative idea is rejected?", type: "options", options: ["Seek feedback and revise it", "Accept it and move on", "Advocate more strongly for it", "Feel discouraged temporarily"], category: "Resilience" },
            { q: "How comfortable are you challenging the status quo at work?", type: "scale", category: "Risk-Taking" },
            { q: "When brainstorming, what is your typical contribution?", type: "options", options: ["Generate many diverse ideas", "Evaluate and refine ideas", "Build upon others' ideas", "Ground ideas in practical reality"], category: "Creative Role" },
            { q: "How often do you bring external inspiration into your work?", type: "scale", category: "Curiosity" },
            { q: "How well does your organization support creative thinking?", type: "scale", category: "Environment" },
            { q: "What fuels your creativity at work?", type: "text", category: "Motivation" },
            { q: "How effectively do you balance innovation with established processes?", type: "scale", category: "Balance" },
            { q: "How willing are you to take calculated risks to achieve better outcomes?", type: "scale", category: "Risk Appetite" },
        ],
        "Problem Solving": [
            { q: "How systematically do you approach a complex workplace problem?", type: "options", options: ["Define > Analyze > Solutions > Test", "Brainstorm first, structure later", "Ask team and management for input", "Research what others have done"], category: "Approach" },
            { q: "How confident are you in solving problems without supervisor input?", type: "scale", category: "Autonomy" },
            { q: "Describe the most complex problem you solved at work:", type: "text", category: "Experience" },
            { q: "How do you react when a solution doesn't work as expected?", type: "options", options: ["Iterate and refine the solution", "Escalate to a senior colleague", "Try a completely different approach", "Document lessons and move forward"], category: "Adaptability" },
            { q: "How well do you use data and evidence in your problem-solving?", type: "scale", category: "Analytical Thinking" },
            { q: "How effectively do you manage time during problem-solving?", type: "scale", category: "Efficiency" },
            { q: "How comfortable are you leading a problem-solving session with the team?", type: "scale", category: "Facilitation" },
            { q: "How often do you identify problems before they escalate?", type: "scale", category: "Proactiveness" },
            { q: "What problem-solving tools or frameworks do you use regularly?", type: "text", category: "Tools" },
            { q: "How well do you handle ambiguity when solving open-ended problems?", type: "scale", category: "Ambiguity Tolerance" },
        ],
    },

    // ============ TEAM LEADER ============
    "Team Leader": {
        Performance: [
            { q: "How consistently does your team deliver on its goals and targets?", type: "scale", category: "Team Performance" },
            { q: "How do you manage underperforming team members?", type: "options", options: ["One-on-one coaching and support plan", "Set clear expectations and monitor", "Involve HR when needed", "Provide additional training opportunities"], category: "People Management" },
            { q: "How clearly do you communicate performance expectations to your team?", type: "scale", category: "Clarity" },
            { q: "Describe your most successful team achievement:", type: "text", category: "Accomplishments" },
            { q: "How effectively do you use data to drive your team's performance decisions?", type: "scale", category: "Data-Driven" },
            { q: "How well do you balance short-term deliverables with long-term goals?", type: "scale", category: "Strategic Thinking" },
            { q: "How proactively do you identify and remove blockers for your team?", type: "scale", category: "Enablement" },
            { q: "How do you keep your team motivated during high-pressure periods?", type: "text", category: "Motivation" },
            { q: "How effectively do you conduct performance reviews?", type: "scale", category: "Feedback Culture" },
            { q: "How often do you celebrate your team's milestones and successes?", type: "scale", category: "Recognition" },
        ],
        Leadership: [
            { q: "What leadership style best describes your approach?", type: "options", options: ["Transformational: big picture vision", "Servant: removing obstacles for team", "Coaching: developing individuals", "Pacesetting: high standards and pace"], category: "Style" },
            { q: "How do you adapt your leadership style to individual team members?", type: "text", category: "Situational Leadership" },
            { q: "How effectively do you make high-stakes decisions under pressure?", type: "scale", category: "Decision Making" },
            { q: "How do you build psychological safety in your team?", type: "options", options: ["Encourage open feedback culture", "Share my own vulnerabilities and mistakes", "Tolerate and learn from failures", "All of the above"], category: "Psychological Safety" },
            { q: "How well do you develop future leaders within your team?", type: "scale", category: "Succession Planning" },
            { q: "How do you handle losing a key team member?", type: "options", options: ["Cross-train in advance", "Restructure responsibilities quickly", "Recruit immediately", "Document knowledge before they leave"], category: "Risk Management" },
            { q: "How effectively do you manage upward (with your own manager)?", type: "scale", category: "Upward Management" },
            { q: "Describe a pivotal leadership decision you've made:", type: "text", category: "Experience" },
            { q: "How well do you communicate the team's vision and purpose?", type: "scale", category: "Vision" },
            { q: "How do you handle dissent or pushback from team members?", type: "options", options: ["Welcome it and use it constructively", "Discuss privately with the individual", "Make the final call while acknowledging", "Revisit the decision if challenged"], category: "Resilience" },
        ],
        Communication: [
            { q: "How clearly do you communicate strategic changes to your team?", type: "scale", category: "Clarity" },
            { q: "How do you ensure information flows effectively across your team?", type: "options", options: ["Regular team meetings and updates", "Direct communication channels", "Shared documentation and wikis", "All of the above"], category: "Information Flow" },
            { q: "How effectively do you give difficult feedback?", type: "scale", category: "Challenging Conversations" },
            { q: "Describe how you handled a miscommunication that impacted your team:", type: "text", category: "Reflection" },
            { q: "How well do you tailor your communication style to different personalities?", type: "scale", category: "Adaptability" },
            { q: "How frequently do you have one-on-one meetings with team members?", type: "options", options: ["Weekly", "Bi-weekly", "Monthly", "Ad hoc as needed"], category: "Connection" },
            { q: "How well do you represent your team's interests to senior leadership?", type: "scale", category: "Advocacy" },
            { q: "How transparent are you with your team about organizational decisions?", type: "scale", category: "Transparency" },
            { q: "How do you handle rumors or misinformation within the team?", type: "options", options: ["Address it directly and factually", "Clarify in team meetings", "Speak to individuals privately", "Escalate to HR if serious"], category: "Trust" },
            { q: "What is the most important communication habit you've developed as a leader?", type: "text", category: "Best Practice" },
        ],
        Teamwork: [
            { q: "How effectively do you foster collaboration between team members?", type: "scale", category: "Collaboration" },
            { q: "How do you handle unhealthy competition within your team?", type: "options", options: ["Redirect to shared goals", "Address directly with individuals", "Restructure team incentives", "Promote collaborative wins instead"], category: "Team Dynamics" },
            { q: "How well does your team trust each other?", type: "scale", category: "Trust" },
            { q: "Describe a time your team overcame a significant challenge together:", type: "text", category: "Resilience" },
            { q: "How proactively do you identify and leverage each team member's strengths?", type: "scale", category: "Strengths-Based" },
            { q: "How well do you build relationships across cross-functional teams?", type: "scale", category: "Cross-Functional" },
            { q: "What team-building practice has been most effective for your team?", type: "text", category: "Best Practice" },
            { q: "How inclusive is your team culture?", type: "scale", category: "Inclusivity" },
            { q: "How do you handle team members who don't collaborate well?", type: "options", options: ["Coach them on team behaviors", "Create structured collaboration opportunities", "Adjust their role to suit independence", "Address it as a performance issue"], category: "Management" },
            { q: "How do you celebrate diversity of thought in your team?", type: "scale", category: "Diversity" },
        ],
        Creativity: [
            { q: "How often do you encourage your team to experiment and take risks?", type: "scale", category: "Innovation Culture" },
            { q: "How do you structure brainstorming or ideation sessions?", type: "options", options: ["Open-ended free brainstorming", "Structured problem-solving workshops", "Individual ideation then group sharing", "Cross-functional innovation sprints"], category: "Process" },
            { q: "Describe the most innovative initiative your team has launched:", type: "text", category: "Innovation Experience" },
            { q: "How do you handle creative failures within your team?", type: "options", options: ["Learn from them openly as a team", "Privately debrief with those involved", "Accept them as part of innovation", "Adjust the process to prevent recurrence"], category: "Failure Culture" },
            { q: "How well do you protect creative time for your team?", type: "scale", category: "Creative Space" },
            { q: "How do you bring in fresh perspectives or external inspiration?", type: "text", category: "Curiosity" },
            { q: "How effectively do you balance innovation with operational efficiency?", type: "scale", category: "Balance" },
            { q: "How often does your team generate ideas that get implemented?", type: "scale", category: "Execution" },
            { q: "How comfortable is your team challenging the current way of doing things?", type: "scale", category: "Psychological Safety" },
            { q: "What is your biggest challenge in fostering creativity in your team?", type: "text", category: "Challenges" },
        ],
        "Problem Solving": [
            { q: "How do you approach complex problems that have no obvious solution?", type: "options", options: ["Involve the team in structured ideation", "Break down into root causes first", "Research industry best practices", "Experiment with small-scale pilots"], category: "Approach" },
            { q: "How effectively do you facilitate team problem-solving sessions?", type: "scale", category: "Facilitation" },
            { q: "Describe a critical team problem you solved under significant pressure:", type: "text", category: "Experience" },
            { q: "How do you balance speed of decision-making with thoroughness?", type: "options", options: ["Assess urgency to calibrate depth", "Always gather sufficient data first", "Make quick calls and adjust later", "Consult key stakeholders quickly"], category: "Decision Making" },
            { q: "How well do you use post-mortems to improve future problem-solving?", type: "scale", category: "Learning" },
            { q: "How effectively do you use tools or frameworks to structure problems?", type: "scale", category: "Methodology" },
            { q: "How do you prevent recurring problems in your team?", type: "options", options: ["Root cause analysis and systemic fixes", "Document and share lessons learned", "Improve processes and workflows", "Regular retrospectives and reviews"], category: "Prevention" },
            { q: "How well do you handle conflicting priorities when solving team problems?", type: "scale", category: "Prioritization" },
            { q: "How transparently do you communicate problem-solving decisions to your team?", type: "scale", category: "Transparency" },
            { q: "What is your most effective strategy for solving ambiguous, long-term problems?", type: "text", category: "Strategy" },
        ],
    },

    // ============ MANAGER ============
    Manager: {
        Performance: [
            { q: "How effectively does your department consistently achieve its strategic objectives?", type: "scale", category: "Strategic Execution" },
            { q: "How do you handle persistent underperformance at the team level?", type: "options", options: ["Structured performance improvement plans", "Coaching and mentoring investment", "Organizational restructuring", "Transparent performance conversations"], category: "Performance Management" },
            { q: "How well do you translate organizational strategy into team-level goals?", type: "scale", category: "Strategy Translation" },
            { q: "Describe a significant organizational performance challenge you successfully navigated:", type: "text", category: "Leadership Experience" },
            { q: "How effectively do you use KPIs and metrics to drive performance?", type: "scale", category: "Data-Driven Management" },
            { q: "How proactively do you identify organizational risks before they impact performance?", type: "scale", category: "Risk Management" },
            { q: "How well do you allocate resources across competing priorities?", type: "options", options: ["Data-driven ROI analysis", "Strategic priority alignment", "Stakeholder negotiation", "Incremental and adaptive allocation"], category: "Resource Management" },
            { q: "How do you maintain team morale during organizational change?", type: "text", category: "Change Management" },
            { q: "How effectively do you develop a performance-driven culture?", type: "scale", category: "Culture" },
            { q: "How do you reinforce accountability at all levels without micromanaging?", type: "scale", category: "Accountability" },
        ],
        Leadership: [
            { q: "How do you develop a shared vision that motivates across different teams?", type: "text", category: "Vision" },
            { q: "How effectively do you navigate organizational politics?", type: "scale", category: "Organizational Savvy" },
            { q: "What is your primary approach to executive decision-making?", type: "options", options: ["Evidence-based and analytical", "Consultative and inclusive", "Intuitive based on deep experience", "Scenario-based and strategic"], category: "Decision Style" },
            { q: "How well do you develop next-generation leaders in your organization?", type: "scale", category: "Talent Development" },
            { q: "Describe a time you led significant organizational change:", type: "text", category: "Change Leadership" },
            { q: "How effectively do you manage board, executive, or cross-departmental relationships?", type: "scale", category: "Stakeholder Management" },
            { q: "How transparent are you with your teams about organizational strategy?", type: "scale", category: "Transparency" },
            { q: "How do you maintain your leadership effectiveness during personal or professional stress?", type: "options", options: ["Self-care and boundary setting", "Delegate more during tough periods", "Seek peer support and mentorship", "Stay focused on team well-being"], category: "Leader Resilience" },
            { q: "How do you balance authority with humility as a senior leader?", type: "text", category: "Humility" },
            { q: "How effectively do you inspire commitment rather than just compliance?", type: "scale", category: "Inspiration" },
        ],
        Communication: [
            { q: "How effectively do you communicate strategic priorities across all levels?", type: "scale", category: "Cascading Communication" },
            { q: "How do you ensure your communication is aligned with the organization's culture?", type: "options", options: ["Model the culture in my own communication", "Align messages with company values", "Seek feedback on communication effectiveness", "Work with HR and communications teams"], category: "Cultural Alignment" },
            { q: "How well do you handle crisis communication affecting your teams?", type: "scale", category: "Crisis Communication" },
            { q: "Describe a high-stakes communication challenge you navigated successfully:", type: "text", category: "Experience" },
            { q: "How effectively do you use storytelling to communicate organizational goals?", type: "scale", category: "Narrative" },
            { q: "How regularly do you create two-way communication channels with your teams?", type: "scale", category: "Feedback Channels" },
            { q: "How transparent are you about organizational challenges with your teams?", type: "scale", category: "Transparency" },
            { q: "How do you adapt your communication for diverse cultural contexts?", type: "options", options: ["Research and educate myself", "Hire diverse communication advisors", "Adapt style based on feedback", "Focus on universal principles"], category: "Diversity" },
            { q: "How well do you represent your organization externally?", type: "scale", category: "External Communication" },
            { q: "What is your most important communication principle as a leader?", type: "text", category: "Philosophy" },
        ],
        Teamwork: [
            { q: "How effectively do you foster collaboration between different departments?", type: "scale", category: "Cross-Functional Collaboration" },
            { q: "How do you break down organizational silos?", type: "options", options: ["Shared goals and joint projects", "Cross-functional team structures", "Joint performance metrics", "Regular cross-department forums"], category: "Silo-Breaking" },
            { q: "How well do you build a culture of psychological safety across your teams?", type: "scale", category: "Culture" },
            { q: "Describe your approach to building high-performing, cohesive teams:", type: "text", category: "Team Building" },
            { q: "How effectively do you manage executive-level team dynamics?", type: "scale", category: "Executive Teamwork" },
            { q: "How do you promote diversity and inclusion within your teams?", type: "options", options: ["Inclusive hiring and promotion practices", "Diverse team composition in projects", "Bias training and awareness", "Inclusive leadership behaviors"], category: "DEI" },
            { q: "How proactively do you recognize and reward collaborative behavior?", type: "scale", category: "Recognition" },
            { q: "Describe your approach to managing conflict between senior leaders or teams:", type: "text", category: "Conflict Resolution" },
            { q: "How effectively do you manage virtual or geographically distributed teams?", type: "scale", category: "Remote Leadership" },
            { q: "How do you measure and improve team collaboration effectiveness?", type: "scale", category: "Measurement" },
        ],
        Creativity: [
            { q: "How effectively do you foster a culture of innovation in your organization?", type: "scale", category: "Innovation Culture" },
            { q: "How do you allocate resources for innovation and experimentation?", type: "options", options: ["Dedicated innovation budget/team", "20% time for exploration", "Ad hoc project-based funding", "Partner with external innovators"], category: "Resource Allocation" },
            { q: "Describe a transformative innovation you championed:", type: "text", category: "Innovation Experience" },
            { q: "How do you balance risk-taking for innovation with organizational stability?", type: "scale", category: "Risk Balance" },
            { q: "How effectively do you use design thinking or similar frameworks?", type: "scale", category: "Innovation Methodology" },
            { q: "How do you reward and recognize innovative thinking in your teams?", type: "options", options: ["Formal innovation awards", "Career advancement opportunities", "Dedicated innovation time", "Visible organizational recognition"], category: "Recognition" },
            { q: "How do you respond to failed innovation attempts?", type: "options", options: ["Celebrate the learning explicitly", "Do a thorough post-mortem analysis", "Protect the team from criticism", "Immediately pivot to what works"], category: "Failure Culture" },
            { q: "How do you stay current with innovations in your field?", type: "text", category: "Learning" },
            { q: "How effectively do you connect organizational creativity to business outcomes?", type: "scale", category: "Business Impact" },
            { q: "What is your vision for your organization's innovative future?", type: "text", category: "Vision" },
        ],
        "Problem Solving": [
            { q: "How effectively do you solve complex, multifaceted organizational problems?", type: "scale", category: "Complex Problem Solving" },
            { q: "What is your primary framework for organizational problem-solving?", type: "options", options: ["Systems thinking approach", "Data and evidence-driven", "Design thinking and empathy", "Strategic scenario planning"], category: "Framework" },
            { q: "Describe the most complex organizational challenge you successfully resolved:", type: "text", category: "Experience" },
            { q: "How effectively do you build organizational problem-solving capability?", type: "scale", category: "Capability Building" },
            { q: "How do you manage the tension between urgency and thoroughness in problem resolution?", type: "scale", category: "Decision Calibration" },
            { q: "How well do you anticipate future organizational problems before they emerge?", type: "scale", category: "Foresight" },
            { q: "How do you leverage external expertise when internal problem-solving reaches its limits?", type: "options", options: ["External consultants and advisors", "Peer networks and benchmarking", "Research and academic partnerships", "Technology and AI solutions"], category: "External Resources" },
            { q: "How transparent are you in sharing problem-solving processes with your organization?", type: "scale", category: "Transparency" },
            { q: "How do you measure the effectiveness of organizational problem-solving initiatives?", type: "scale", category: "Measurement" },
            { q: "What is your most important principle in leading through complex organizational uncertainty?", type: "text", category: "Philosophy" },
        ],
    },

    // ============ TEACHER ============
    Teacher: {
        Performance: [
            { q: "How effectively do your students achieve the learning outcomes you set?", type: "scale", category: "Teaching Effectiveness" },
            { q: "How do you adapt your teaching when students are struggling to understand content?", type: "options", options: ["Use multiple teaching methods", "Provide one-on-one support", "Simplify and scaffold content", "Encourage peer teaching"], category: "Differentiation" },
            { q: "How consistently do you reflect on and improve your teaching practice?", type: "scale", category: "Reflective Practice" },
            { q: "Describe your most successful teaching experience:", type: "text", category: "Accomplishments" },
            { q: "How effectively do you use formative assessment to guide instruction?", type: "scale", category: "Assessment for Learning" },
            { q: "How well do you manage a diverse classroom with varying learning needs?", type: "scale", category: "Inclusivity" },
            { q: "How do you maintain student engagement throughout a lesson?", type: "options", options: ["Varied activities and interaction", "Real-world applications of content", "Student-led discussion and inquiry", "Technology-enhanced learning"], category: "Engagement" },
            { q: "Describe your approach to professional development:", type: "text", category: "Growth" },
            { q: "How well do you connect curriculum content to students' real-life experiences?", type: "scale", category: "Relevance" },
            { q: "How effectively do you collaborate with other teachers to improve student outcomes?", type: "scale", category: "Professional Collaboration" },
        ],
        Leadership: [
            { q: "How do you lead and influence your department or school beyond your classroom?", type: "text", category: "Teacher Leadership" },
            { q: "How effectively do you mentor new or junior teachers?", type: "scale", category: "Mentoring" },
            { q: "How do you lead curriculum development or educational initiatives?", type: "options", options: ["Lead the design and implementation", "Collaborate as a key contributor", "Support and advise the lead team", "Implement with feedback and iteration"], category: "Curriculum Leadership" },
            { q: "How well do you advocate for students' needs to school leadership?", type: "scale", category: "Student Advocacy" },
            { q: "How effectively do you lead parent or community engagement initiatives?", type: "scale", category: "Community Leadership" },
            { q: "Describe a leadership decision you made that positively impacted your school:", type: "text", category: "Impact" },
            { q: "How do you manage competing demands from administration, parents, and students?", type: "options", options: ["Prioritize student outcomes always", "Communicate proactively with all parties", "Set clear boundaries and expectations", "Escalate to leadership when needed"], category: "Management" },
            { q: "How well do you inspire a love of learning in reluctant students?", type: "scale", category: "Inspiration" },
            { q: "How do you promote teacher well-being in your educational community?", type: "scale", category: "Well-being" },
            { q: "What is your educational leadership philosophy?", type: "text", category: "Philosophy" },
        ],
        Communication: [
            { q: "How effectively do you communicate learning expectations and feedback to students?", type: "scale", category: "Student Communication" },
            { q: "How proactively do you communicate with parents about student progress?", type: "scale", category: "Parent Communication" },
            { q: "How do you adapt your communication style to support diverse student needs?", type: "options", options: ["Use multiple communication formats", "Adjust language complexity appropriately", "Use visual aids and demonstrations", "All of the above"], category: "Differentiation" },
            { q: "Describe a difficult communication experience with a parent or administrator:", type: "text", category: "Challenging Communication" },
            { q: "How well do you facilitate productive class discussions?", type: "scale", category: "Discussion Facilitation" },
            { q: "How effectively do you communicate within your teaching team?", type: "scale", category: "Collaboration" },
            { q: "How well do you give students feedback that motivates rather than discourages?", type: "scale", category: "Feedback Quality" },
            { q: "How do you handle sensitive topics that arise in classroom discussion?", type: "options", options: ["Address them calmly with all perspectives", "Refer to school guidelines", "Use it as a learning moment", "Redirect and discuss privately if needed"], category: "Sensitivity" },
            { q: "How well do you communicate the purpose of learning to your students?", type: "scale", category: "Purpose-Driven Teaching" },
            { q: "What communication strategy has most improved your teaching effectiveness?", type: "text", category: "Best Practice" },
        ],
        Teamwork: [
            { q: "How effectively do you collaborate with teaching colleagues?", type: "scale", category: "Collaboration" },
            { q: "How do you contribute to a positive school culture beyond your classroom?", type: "text", category: "Culture" },
            { q: "How well do you co-plan and co-teach with subject or grade-level partners?", type: "scale", category: "Co-Teaching" },
            { q: "When you disagree with a school-wide decision, how do you respond?", type: "options", options: ["Raise concerns through proper channels", "Implement it while providing feedback", "Discuss with colleagues for perspective", "Propose alternatives to leadership"], category: "Professional Conduct" },
            { q: "How proactively do you share teaching resources and strategies with colleagues?", type: "scale", category: "Knowledge Sharing" },
            { q: "Describe your most effective collegial collaboration experience:", type: "text", category: "Reflection" },
            { q: "How well do you support colleagues who are struggling with teaching challenges?", type: "scale", category: "Support" },
            { q: "How effectively do you work with teaching assistants or support staff?", type: "scale", category: "Team Effectiveness" },
            { q: "What makes your school team function most effectively?", type: "text", category: "Team Insight" },
            { q: "How do you promote a collaborative rather than competitive atmosphere among staff?", type: "scale", category: "Culture Building" },
        ],
        Creativity: [
            { q: "How often do you design innovative and engaging lessons?", type: "scale", category: "Lesson Innovation" },
            { q: "Describe your most creative teaching strategy or lesson design:", type: "text", category: "Innovation" },
            { q: "How do you use technology creatively in your classroom?", type: "options", options: ["Gamification and educational apps", "Virtual reality and simulations", "Student-created digital content", "AI-powered personalized learning"], category: "EdTech" },
            { q: "How well do you foster student creativity and creative thinking?", type: "scale", category: "Student Creativity" },
            { q: "How do you incorporate project-based or experiential learning?", type: "scale", category: "Experiential Learning" },
            { q: "How do you adapt when a creative lesson doesn't land as expected?", type: "options", options: ["Reflect and redesign the approach", "Get student feedback immediately", "Try variations in the next lesson", "Consult with a trusted colleague"], category: "Adaptability" },
            { q: "How creatively do you differentiate instruction for diverse learners?", type: "scale", category: "Differentiation" },
            { q: "What is your most innovative teaching approach?", type: "text", category: "Signature Practice" },
            { q: "How do you stay creatively inspired and avoid teaching burnout?", type: "text", category: "Sustainability" },
            { q: "How comfortable are you experimenting with entirely new teaching methodologies?", type: "scale", category: "Risk-Taking" },
        ],
        "Problem Solving": [
            { q: "How effectively do you diagnose and address student learning difficulties?", type: "scale", category: "Learning Diagnosis" },
            { q: "When classroom behavior disrupts learning, what is your primary response?", type: "options", options: ["Address root causes, not symptoms", "Implement a restorative practice approach", "Engage the student privately", "Adjust the learning environment or activity"], category: "Behavior Management" },
            { q: "Describe a complex classroom or school problem you solved:", type: "text", category: "Problem Solving Experience" },
            { q: "How well do you problem-solve with parents when their child is struggling?", type: "scale", category: "Partnership" },
            { q: "How effectively do you solve resource constraints in your teaching?", type: "scale", category: "Resourcefulness" },
            { q: "How do you tackle complex curriculum design challenges?", type: "options", options: ["Backwards design from outcomes", "Research best-practice pedagogies", "Collaborate with experienced colleagues", "Pilot and iterate with student feedback"], category: "Curriculum Problem Solving" },
            { q: "How proactively do you identify students at academic or social risk?", type: "scale", category: "Early Intervention" },
            { q: "How well do you adapt when school-wide challenges impact your classroom?", type: "scale", category: "Adaptability" },
            { q: "What is your most effective strategy for solving persistent student learning problems?", type: "text", category: "Strategy" },
            { q: "How do you help students develop their own problem-solving skills?", type: "text", category: "Student Empowerment" },
        ],
    },
};

/**
 * Get questions for a specific role + purpose combination
 * Returns 10 questions from the bank (or all if fewer than 10)
 */
function getQuestions(role, purpose) {
    const bank = QUESTION_BANK[role] && QUESTION_BANK[role][purpose];
    if (!bank) return [];
    // Shuffle slightly for variability but keep first 10
    const copy = [...bank];
    return copy.slice(0, Math.min(12, copy.length));
}

// Export for use in form.js
window.getQuestions = getQuestions;
